version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-flour
    env_file: .env

    ports:
      - "4324:${PORT}"

    restart: unless-stopped
  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:latest
    environment:
      PUID: 1000
      PGID: 1000
      FLATNOTES_AUTH_TYPE: "none"
      FLATNOTES_SECRET_KEY: "aLongRandomSeriesOfCharacters"
    volumes:
      - "./data:/data"
        # Optional. Allows you to save the search index in a different location:
        # - "./index:/data/.flatnotes"
    ports:
      - "8280:8080"
    restart: unless-stopped
